Repository g12-4soat/techlanches-pedido, pull requests merged in 2024-07, with the labels that each got.

#16 Feature/saga coreografada
  src/TechLanches.Pedido/Adapter/Driven/TechLanches.Adapter.RabbitMq/Messaging/IRabbitMqService.cs
  src/TechLanches.Pedido/Adapter/Driven/TechLanches.Adapter.RabbitMq/Messaging/RabbitMqService.cs
  src/TechLanches.Pedido/Adapter/Driven/TechLanches.Adapter.RabbitMq/Options/RabbitOptions.cs
  src/TechLanches.Pedido/Adapter/Driven/TechLanches.Adapter.RabbitMq/PedidoCriadoMessage.cs
  src/TechLanches.Pedido/Adapter/Driven/TechLanches.Adapter.RabbitMq/PedidoStatusMessage.cs
  src/TechLanches.Pedido/Adapter/Driven/TechLanches.Adapter.RabbitMq/TechLanches.Adapter.RabbitMq.csproj
  src/TechLanches.Pedido/Adapter/Driven/TechLanches.Adapter.SqlServer/DatabaseConfig.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Controllers/Interfaces/IPedidoController.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Controllers/PedidoController.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/DTOs/PagamentoResponseDTO.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Gateways/PagamentoGateway.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/UseCases/Checkout/CheckoutUseCase.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Configuration/DependecyInjectionConfig.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Configuration/RegisterMapsConfig.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Endpoints/CheckoutEndpoints.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Program.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/TechLanches.Pedido.API.csproj
  src/TechLanches.Pedido/TechLanches.Pedido.API/appsettings.Development.json
  src/TechLanches.Pedido/TechLanches.Pedido.API/appsettings.json
  src/TechLanches.Pedido/TechLanches.Pedido.Consumer/PedidoConsumerHostedService.cs
  src/TechLanches.Pedido/TechLanches.Pedido.Consumer/TechLanches.Pedido.Consumer.csproj
  src/TechLanches.Pedido/TechLanches.Pedido.sln
  test/TechLanches.Pedido.Tests/BDDTests/Services/CheckoutTest.cs
  test/TechLanches.Pedido.Tests/BDDTests/Services/PedidoTest.cs
Labels: enhancement

#20 Update README.md
  README.md
Labels: documentation

#21 endpoint pedidos por cliente
  src/TechLanches.Pedido/TechLanches.Pedido.API/Endpoints/PedidoEndpoints.cs
Labels: bug
