Repository g12-4soat/techlanches-pedido, pull requests merged in 2024-05, with the labels that each got.

#2 Melhorias Microserviço de Pedido
  src/TechLanches.Pedido/Core/TechLanches.Application/Constantes/Constants.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Controllers/CheckoutController.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Controllers/Interfaces/ICheckoutController.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/DTOs/PagamentoRequestDTO.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/DTOs/PagamentoResponseDTO.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Gateways/Interfaces/IPagamentoGateway.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Gateways/PagamentoGateway.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/TechLanches.Application.csproj
  src/TechLanches.Pedido/Core/TechLanches.Application/UseCases/Checkout/CheckoutUseCase.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Configuration/RegisterMapsConfig.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Endpoints/CheckoutEndpoints.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Endpoints/PedidoEndpoints.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Middlewares/JwtTokenMiddleware.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Program.cs
Labels: enhancement

#4 Feature/melhorias testes
  src/TechLanches.Pedido/Adapter/Driven/TechLanches.Adapter.RabbitMq/Messaging/IRabbitMqService.cs
  src/TechLanches.Pedido/Adapter/Driven/TechLanches.Adapter.RabbitMq/Messaging/RabbitMqService.cs
  src/TechLanches.Pedido/Adapter/Driven/TechLanches.Adapter.SqlServer/DataSeeder.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/AppSettings.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Controllers/Interfaces/IPedidoController.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Controllers/PedidoController.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/DTOs/PedidoResponseDTO.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/DTOs/UserTokenDTO.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Options/ApplicationOptions.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Presenters/PedidoPresenter.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/UseCases/Checkout/CheckoutUseCase.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/UseCases/Pedidos/PedidoUseCases.cs
  src/TechLanches.Pedido/Core/TechLanches.Core/DomainEvent.cs
  src/TechLanches.Pedido/Core/TechLanches.Core/Entity.cs
  src/TechLanches.Pedido/Core/TechLanches.Core/Enumeration.cs
  src/TechLanches.Pedido/Core/TechLanches.Core/ValueObject.cs
  src/TechLanches.Pedido/Core/TechLanches.Domain/Aggregates/Pagamento.cs
  src/TechLanches.Pedido/Core/TechLanches.Domain/Aggregates/Pedido.cs
  src/TechLanches.Pedido/Core/TechLanches.Domain/Aggregates/Usuario.cs
  src/TechLanches.Pedido/Core/TechLanches.Domain/Entities/Cliente.cs
  src/TechLanches.Pedido/Core/TechLanches.Domain/ValueObjects/Email.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Configuration/RegisterMapsConfig.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Endpoints/CheckoutEndpoints.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Program.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/TechLanches.Pedido.API.http
  test/TechLanches.Pedido.Tests/BDDTests/Services/CheckoutTest.cs
  test/TechLanches.Pedido.Tests/BDDTests/Services/PedidoTest.cs
  test/TechLanches.Pedido.Tests/BDDTests/Services/ProdutoTest.cs
  test/TechLanches.Pedido.Tests/Fixtures/PedidoFixture.cs
  test/TechLanches.Pedido.Tests/UnitTests/Core/Assets/Address.cs
  test/TechLanches.Pedido.Tests/UnitTests/Core/ValueObjectTest.cs
  test/TechLanches.Pedido.Tests/UnitTests/Domain/PedidoTest.cs
Labels: bug, documentation, enhancement

#6 melhorias middleware + code coverage
  src/TechLanches.Pedido/Core/TechLanches.Core/DomainException.cs
  src/TechLanches.Pedido/Core/TechLanches.Core/Entity.cs
  src/TechLanches.Pedido/Core/TechLanches.Core/Enumeration.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Configuration/DependecyInjectionConfig.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Endpoints/CheckoutEndpoints.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Middlewares/JwtTokenMiddleware.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Program.cs
Labels: enhancement

#7 fix dockerfile
  src/TechLanches.Pedido/Dockerfile
  src/TechLanches.Pedido/TechLanches.Pedido.API/Configuration/AuthenticationConfig.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/appsettings.json
Labels: bug, enhancement

#9 Update README.md
  README.md
Labels: documentation

#12 correções de testes integrados
  src/TechLanches.Pedido/Core/TechLanches.Application/Controllers/PedidoController.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Gateways/Interfaces/IPagamentoGateway.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Gateways/PagamentoGateway.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Presenters/Interfaces/IPedidoPresenter.cs
  src/TechLanches.Pedido/Core/TechLanches.Application/Presenters/PedidoPresenter.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Configuration/ApplicationBuilderConfig.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Endpoints/CheckoutEndpoints.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Middlewares/GlobalErrorHandlingMiddleware.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Middlewares/JwtTokenMiddleware.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Middlewares/RequestLoggingMiddleware.cs
  src/TechLanches.Pedido/TechLanches.Pedido.API/Program.cs
  test/TechLanches.Pedido.Tests/UnitTests/Application/PagamentoGatewayTest.cs
  test/TechLanches.Pedido.Tests/UnitTests/Core/ValueObjectTest.cs
Labels: bug

#10 Add files via upload
  docs/TechLanches.postman_environment.json
  docs/techlanchespedido.postman_collection.json
Labels: documentation
